name: Update Badges

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  update-badges:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update README badges
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            
            // README.mdファイルを読み込み
            let readmeContent = '';
            try {
              readmeContent = fs.readFileSync('README.md', 'utf8');
            } catch (error) {
              console.log('README.md not found, creating new one');
              readmeContent = `# ${context.repo.repo}\n\n`;
            }
            
            // バッジセクションを作成
            const badges = `
![CI/CD Pipeline](https://github.com/${context.repo.owner}/${context.repo.repo}/workflows/CI%2FCD%20Pipeline/badge.svg)
![Coverage](https://codecov.io/gh/${context.repo.owner}/${context.repo.repo}/branch/main/graph/badge.svg)
![Node Version](https://img.shields.io/badge/node-%3E%3D18-brightgreen)
![TypeScript](https://img.shields.io/badge/TypeScript-5.1+-blue)
![License](https://img.shields.io/github/license/${context.repo.owner}/${context.repo.repo})
![Last Commit](https://img.shields.io/github/last-commit/${context.repo.owner}/${context.repo.repo})
`;
            
            // バッジが既に存在する場合は更新、存在しない場合は追加
            if (readmeContent.includes('![CI/CD Pipeline]')) {
              // 既存のバッジセクションを置換
              readmeContent = readmeContent.replace(
                /!\[CI\/CD Pipeline\].*?\n(?:\![^\n]*\n)*/g,
                badges.trim() + '\n'
              );
            } else {
              // タイトルの後にバッジを追加
              readmeContent = readmeContent.replace(
                /(#[^\n]*\n)/,
                `$1\n${badges}\n`
              );
            }
            
            // ファイルに書き戻し
            fs.writeFileSync('README.md', readmeContent);
            
            console.log('README.md updated with latest badges');

